accounts/urls.py
from django.urls import path

from .views import SignUpView

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

cookie_stands/urls.py
from django.urls import path
from .views import CookieStandList, CookieStandDetail

urlpatterns = [
    path("", CookieStandList.as_view(), name="CookieStand_list"),
    path("<int:pk>/", CookieStandDetail.as_view(), name="Cookiestand_detail"),
]

project/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework_simplejwt import views as jwt_views
from .views import MyTokenObtainPairView
from django.views.generic.base import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/v1/cookie_stands/", include("cookie_stands.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path('api/token/', MyTokenObtainPairView.as_view(), name='token_obtain_pair'
    ),
    path(
        "api/token/refresh/",
        jwt_views.TokenRefreshView.as_view(),
        name="token_refresh",
    ),
    path("cookie_stands/", include("cookie_stands.urls_front")),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("about/", TemplateView.as_view(template_name="about.html"), name="about"),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    pass
    # add additional fields in here

    def __str__(self):
        return self.username

cookie_stands/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse


class CookieStand(models.Model):
    location = models.CharField(max_length=256)
    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, null=True, blank=True)
    description = models.TextField(blank=True)
    hourly_sales = models.JSONField(default=list, null=True)
    minimum_customers_per_hour = models.IntegerField(default=0)
    maximum_customers_per_hour = models.IntegerField(default=0)
    average_cookies_per_sale = models.FloatField(default=0)

    def __str__(self):
        return self.location

    def __str__(self):
        return self.owner


    def get_absolute_url(self):
        return reverse('cookiestand_detail', args=[str(self.id)])

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ("username", "email")


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ("username", "email")

accounts/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView

from .forms import CustomUserCreationForm

class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

cookie_stands/views.py
from rest_framework.generics import (
    ListCreateAPIView,
    RetrieveUpdateDestroyAPIView,
)
from .models import CookieStand
from .permissions import IsOwnerOrReadOnly
from .serializers import CookieStandSerializer


class CookieStandList(ListCreateAPIView):
    queryset = CookieStand.objects.all()
    serializer_class = CookieStandSerializer


class CookieStandDetail(RetrieveUpdateDestroyAPIView):
    permission_classes = (IsOwnerOrReadOnly,)
    queryset = CookieStand.objects.all()
    serializer_class = CookieStandSerializer

project/views.py
from rest_framework_simplejwt.serializers import TokenObtainPairSerializer
from rest_framework_simplejwt.views import TokenObtainPairView


class MyTokenObtainPairSerializer(TokenObtainPairSerializer):
    @classmethod
    def get_token(cls, user):
        token = super().get_token(user)

        # Add custom claims
        token["email"] = user.email
        token["username"] = user.username
        # ...

        return token


class MyTokenObtainPairView(TokenObtainPairView):
    serializer_class = MyTokenObtainPairSerializer

templates/CookieStands/CookieStand_create.html
{% extends 'base.html' %}

{% block content %}
  <div class="w-full max-w-sm p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-6 md:p-8 dark:bg-gray-800 dark:border-gray-700">
    <form class="space-y-6" method="POST">
      {% csrf_token %}
      <h5 class="text-xl font-medium text-gray-900 dark:text-white">Create a cookie stand</h5>


      <div>
        <label for="id_location" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Location</label>
        <input type="text" name="location" id="id_location"
               class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
               placeholder="e.g. Amman" required>
      </div>
      <div>
        <label for="id_owner" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Owner</label>
        <select name="owner" id="id_owner" class="js-select2">
          {% for value, choice in form.fields.owner.choices %}
            <option value="{{ value }}">{{ choice }}</option>
          {% endfor %}
        </select>
      </div>
      <div>
        <label for="id_description" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Description</label>
        <textarea name="description" id="id_description"
                  class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
                  placeholder="Enter a description"></textarea>
      </div>
      <div>
        <label for="id_hourly_sales" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Hourly Sales</label>
        <input type="text" name="hourly_sales" id="id_hourly_sales"
               class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
               placeholder="Enter hourly sales data">
      </div>
      <div>
        <label for="id_min_customers" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Minimum Customers per Hour</label>
        <input type="number" name="minimum_customers_per_hour" id="id_min_customers"
               class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
               min="0" required>
      </div>
      <div>
        <label for="id_max_customers" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Maximum Customers per Hour</label>
        <input type="number" name="maximum_customers_per_hour" id="id_max_customers"
               class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
               min="0" required>
      </div>
      <div>
        <label for="id_avg_cookies" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Average Cookies per Sale</label>
        <input type="number" name="average_cookies_per_sale" id="id_avg_cookies"
               class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
               min="0" step="0.01" required>
      </div>
      <button type="submit"
              class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
        Create
      </button>
    </form>
  </div>
{% endblock content %}

templates/CookieStands/CookieStand_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete cookie stand</h1>
  <form method="POST">
  {% csrf_token %}
    <p>Do you really want to delete "{{ cookiestand.location }}"?</p>
    <input type="submit" value="OK">
  </form>
{% endblock content %}

templates/CookieStands/CookieStand_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="space-y-8 p-6 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">

  <div class="flex">

    <h5 class=" flex-auto mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">{{ cookiestand.name }}</h5>


    <a href="{% url 'CookieStand_update' cookiestand.pk %}">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6 text-blue-600">
        <path
          d="M21.731 2.269a2.625 2.625 0 00-3.712 0l-1.157 1.157 3.712 3.712 1.157-1.157a2.625 2.625 0 000-3.712zM19.513 8.199l-3.712-3.712-8.4 8.4a5.25 5.25 0 00-1.32 2.214l-.8 2.685a.75.75 0 00.933.933l2.685-.8a5.25 5.25 0 002.214-1.32l8.4-8.4z" />
        <path
          d="M5.25 5.25a3 3 0 00-3 3v10.5a3 3 0 003 3h10.5a3 3 0 003-3V13.5a.75.75 0 00-1.5 0v5.25a1.5 1.5 0 01-1.5 1.5H5.25a1.5 1.5 0 01-1.5-1.5V8.25a1.5 1.5 0 011.5-1.5h5.25a.75.75 0 000-1.5H5.25z" />
      </svg>

    </a>

    <a href="{% url 'CookieStand_delete' cookiestand.pk %}">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6 text-red-600">
        <path fill-rule="evenodd"
          d="M16.5 4.478v.227a48.816 48.816 0 013.878.512.75.75 0 11-.256 1.478l-.209-.035-1.005 13.07a3 3 0 01-2.991 2.77H8.084a3 3 0 01-2.991-2.77L4.087 6.66l-.209.035a.75.75 0 01-.256-1.478A48.567 48.567 0 017.5 4.705v-.227c0-1.564 1.213-2.9 2.816-2.951a52.662 52.662 0 013.369 0c1.603.051 2.815 1.387 2.815 2.951zm-6.136-1.452a51.196 51.196 0 013.273 0C14.39 3.05 15 3.684 15 4.478v.113a49.488 49.488 0 00-6 0v-.113c0-.794.609-1.428 1.364-1.452zm-.355 5.945a.75.75 0 10-1.5.058l.347 9a.75.75 0 101.499-.058l-.346-9zm5.48.058a.75.75 0 10-1.498-.058l-.347 9a.75.75 0 001.5.058l.345-9z"
          clip-rule="evenodd" />
      </svg>
    </a>

  </div>

  <h5 class="flex-auto mb-2 text-md font-bold tracking-tight text-gray-900 dark:text-white">owned by : {{ cookiestand.owner }}</h5>


  <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">{{ cookiestand.description }}</p>






{% endblock content %}

templates/CookieStands/CookieStand_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

  <div class="space-y-8 p-8">

    <h1 class="text-4xl text-center">All the cookie stands</h1>
    <div
      class="w-1/2 mx-auto text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-lg dark:bg-gray-700 dark:border-gray-600 dark:text-white">
      {% for cookiestand in cookie_stands %}
        <a href="{% url 'CookieStand_detail' cookiestand.pk %}" aria-current="true"
           class="block w-full px-4 py-4 text-white bg-blue-700 border-b border-gray-200 rounded-t-lg cursor-pointer dark:bg-gray-800 dark:border-gray-600">
          {{ cookiestand.location }}
          {{ cookiestand.description }}
        </a>
      {% endfor %}
    </div>

  </div>

{% endblock content %}

templates/CookieStands/CookieStand_update.html
{% extends 'base.html' %}

{% block content %}
  {#  <h1>Update cookiestand</h1>#}
  {#  <form method="POST">#}
  {##}
  {#    {{ form.as_p }}#}
  {#    <input type="submit" value="SAVE">#}
  {#  </form>#}

  <div
    class="w-full max-w-sm p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-6 md:p-8 dark:bg-gray-800 dark:border-gray-700">
    <form class="space-y-6" method="POST">
      {% csrf_token %}
      <h5 class="text-xl font-medium text-gray-900 dark:text-white">Update a cookiestand</h5>
      <div>
        <label for="id_name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Name</label>
        <input type="text" name="name" id="id_name"
               class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
               required value="{{ cookiestand.name }}">

      </div>
      <div>
        <label for="id_rating" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Rating</label>
        <input type="number" name="rating" id="id_rating"
               class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
               value="{{ cookiestand.rating }}" min="0" max="5" required>
      </div>
      <div>
        <label for="id_reviewer" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Reviewer</label>
        <select name="reviewer" id="id_reviewer">
          {% for value, choice in form.fields.reviewer.choices %}
            <option value="{{ value }}" {% if value == cookiestand.reviewer.id %}selected{% endif %}>{{ choice }}</option>
          {% endfor %}
        </select>
      </div>

      <div>
        <label for="id_description"
               class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Description</label>
        <textarea name="description" id="id_description"
                  class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
                  placeholder="e.g. Celery gets a bad wrap" required>{{ cookiestand.description }}</textarea>
      </div>


      <button type="submit"
              class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
        SAVE
      </button>

    </form>
  </div>
{% endblock content %}

templates/about.html
{% extends 'base.html' %}

{% block content %}

<div class="w-3/4 mx-auto max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
    <div class="flex justify-end px-4 pt-4">
        <button id="dropdownButton" data-dropdown-toggle="dropdown" class="inline-block text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 focus:ring-4 focus:outline-none focus:ring-gray-200 dark:focus:ring-gray-700 rounded-lg text-sm p-1.5" type="button">
            <span class="sr-only">Open dropdown</span>
            <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M6 10a2 2 0 11-4 0 2 2 0 014 0zM12 10a2 2 0 11-4 0 2 2 0 014 0zM16 12a2 2 0 100-4 2 2 0 000 4z"></path></svg>
        </button>
        <!-- Dropdown menu -->
        <div id="dropdown" class="z-10 hidden text-base list-none bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700">
            <ul class="py-2" aria-labelledby="dropdownButton">
            <li>
                <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Edit</a>
            </li>
            <li>
                <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Export Data</a>
            </li>
            <li>
                <a href="#" class="block px-4 py-2 text-sm text-red-600 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Delete</a>
            </li>
            </ul>
        </div>
    </div>
    <div class="flex flex-col items-center pb-10 px-4">
        <img class="w-96 h-96 mb-3 rounded-full shadow-lg" src="https://placekeanu.com/200/150" alt="Keanu image"/>
        <h5 class="mb-1 text-xl font-medium text-gray-900 dark:text-white">Not Keanu Reeves</h5>
        <span class="text-sm text-gray-500 dark:text-gray-400">Full Stack Developer</span>
        <div class="flex mt-4 space-x-3 md:mt-6">
            <a href="#" class="inline-flex items-center px-4 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Add friend</a>
            <a href="#" class="inline-flex items-center px-4 py-2 text-sm font-medium text-center text-gray-900 bg-white border border-gray-300 rounded-lg hover:bg-gray-100 focus:ring-4 focus:outline-none focus:ring-gray-200 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-700 dark:focus:ring-gray-700">Message</a>
        </div>
    </div>
</div>

{% endblock content %}

templates/cookie_stands/cookiestand_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete cookiestand</h1>
  <form method="POST">
  {% csrf_token %}
    <p>Do you really want to delete "{{ cookiestand.name }}"?</p>
    <input type="submit" value="OK">
  </form>
{% endblock content %}

templates/cookie_stands/cookiestand_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

  <div class="space-y-8 p-8">

    <h1 class="text-4xl text-center">All the cookiestands</h1>
    <div
      class="w-1/2 mx-auto text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-lg dark:bg-gray-700 dark:border-gray-600 dark:text-white">
      {% for cookiestand in cookiestands %}
        <a href="{% url 'cookiestand_detail' cookiestand.pk %}" aria-current="true"
           class="block w-full px-4 py-4 text-white bg-blue-700 border-b border-gray-200 rounded-t-lg cursor-pointer dark:bg-gray-800 dark:border-gray-600">
          {{ cookiestand.name }}
        </a>
      {% endfor %}
    </div>

  </div>

{% endblock content %}

templates/cookie_stands/cookiestand_update.html
{% extends 'base.html' %}

{% block content %}
  {#  <h1>Update cookiestand</h1>#}
  {#  <form method="POST">#}
  {##}
  {#    {{ form.as_p }}#}
  {#    <input type="submit" value="SAVE">#}
  {#  </form>#}

  <div
    class="w-full max-w-sm p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-6 md:p-8 dark:bg-gray-800 dark:border-gray-700">
    <form class="space-y-6" method="POST">
      {% csrf_token %}
      <h5 class="text-xl font-medium text-gray-900 dark:text-white">Update a cookiestand</h5>
      <div>
        <label for="id_name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Name</label>
        <input type="text" name="name" id="id_name"
               class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
               required value="{{ cookiestand.name }}">

      </div>
      <div>
        <label for="id_rating" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Rating</label>
        <input type="number" name="rating" id="id_rating"
               class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
               value="{{ cookiestand.rating }}" min="0" max="5" required>
      </div>
      <div>
        <label for="id_reviewer" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Reviewer</label>
        <select name="reviewer" id="id_reviewer">
          {% for value, choice in form.fields.reviewer.choices %}
            <option value="{{ value }}" {% if value == cookiestand.reviewer.id %}selected{% endif %}>{{ choice }}</option>
          {% endfor %}
        </select>
      </div>

      <div>
        <label for="id_description"
               class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Description</label>
        <textarea name="description" id="id_description"
                  class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
                  placeholder="e.g. Celery gets a bad wrap" required>{{ cookiestand.description }}</textarea>
      </div>


      <button type="submit"
              class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
        SAVE
      </button>

    </form>
  </div>
{% endblock content %}

templates/things/thing_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Thing</h1>
  <form method="POST">
  {% csrf_token %}
    <p>Do you really want to delete "{{ thing.name }}"?</p>
    <input type="submit" value="OK">
  </form>
{% endblock content %}

templates/things/thing_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

  <div class="space-y-8 p-8">

    <h1 class="text-4xl text-center">All the Things</h1>
    <div
      class="w-1/2 mx-auto text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-lg dark:bg-gray-700 dark:border-gray-600 dark:text-white">
      {% for thing in things %}
        <a href="{% url 'thing_detail' thing.pk %}" aria-current="true"
           class="block w-full px-4 py-4 text-white bg-blue-700 border-b border-gray-200 rounded-t-lg cursor-pointer dark:bg-gray-800 dark:border-gray-600">
          {{ thing.name }}
        </a>
      {% endfor %}
    </div>

  </div>

{% endblock content %}

templates/things/thing_update.html
{% extends 'base.html' %}

{% block content %}
  {#  <h1>Update Thing</h1>#}
  {#  <form method="POST">#}
  {##}
  {#    {{ form.as_p }}#}
  {#    <input type="submit" value="SAVE">#}
  {#  </form>#}

  <div
    class="w-full max-w-sm p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-6 md:p-8 dark:bg-gray-800 dark:border-gray-700">
    <form class="space-y-6" method="POST">
      {% csrf_token %}
      <h5 class="text-xl font-medium text-gray-900 dark:text-white">Update a Thing</h5>
      <div>
        <label for="id_name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Name</label>
        <input type="text" name="name" id="id_name"
               class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
               required value="{{ thing.name }}">

      </div>
      <div>
        <label for="id_rating" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Rating</label>
        <input type="number" name="rating" id="id_rating"
               class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
               value="{{ thing.rating }}" min="0" max="5" required>
      </div>
      <div>
        <label for="id_reviewer" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Reviewer</label>
        <select name="reviewer" id="id_reviewer">
          {% for value, choice in form.fields.reviewer.choices %}
            <option value="{{ value }}" {% if value == thing.reviewer.id %}selected{% endif %}>{{ choice }}</option>
          {% endfor %}
        </select>
      </div>

      <div>
        <label for="id_description"
               class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Description</label>
        <textarea name="description" id="id_description"
                  class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
                  placeholder="e.g. Celery gets a bad wrap" required>{{ thing.description }}</textarea>
      </div>


      <button type="submit"
              class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
        SAVE
      </button>

    </form>
  </div>
{% endblock content %}